version: '3.8'

volumes:
  wordpress_vol:
  

networks:
  wordpress_net:
    driver: bridge

services:
  wp-web:
    image: wordpress
    networks:
      - wordpress_net
    ports:
      - 8082:80
    volumes:
      - wordpress_vol:/var/www/html  

      